#!/usr/bin/env php
<?php

$autoloaders = [
    dirname(__DIR__) . DIRECTORY_SEPARATOR . 'autoload.php',
    __DIR__ . DIRECTORY_SEPARATOR . 'vendor' . DIRECTORY_SEPARATOR . 'autoload.php',
];

foreach ($autoloaders as $autoloader) {
    if (is_readable($autoloader)) {
        require_once $autoloader;
        break;
    }

}

(new \WPEmergeMagic\Bootstrap)->handle();

exit;